// Built-in drug database for Medications autocomplete.

export const DRUG_DATABASE = [
  {name:"Metformin",generic:"Glucophage",strengths:["500mg","850mg","1000mg"]},
  {name:"Lisinopril",generic:"Prinivil",strengths:["5mg","10mg","20mg","40mg"]},
  {name:"Amlodipine",generic:"Norvasc",strengths:["2.5mg","5mg","10mg"]},
  {name:"Atorvastatin",generic:"Lipitor",strengths:["10mg","20mg","40mg","80mg"]},
  {name:"Rosuvastatin",generic:"Crestor",strengths:["5mg","10mg","20mg","40mg"]},
  {name:"Simvastatin",generic:"Zocor",strengths:["10mg","20mg","40mg","80mg"]},
  {name:"Omeprazole",generic:"Prilosec",strengths:["10mg","20mg","40mg"]},
  {name:"Pantoprazole",generic:"Protonix",strengths:["20mg","40mg"]},
  {name:"Esomeprazole",generic:"Nexium",strengths:["20mg","40mg"]},
  {name:"Losartan",generic:"Cozaar",strengths:["25mg","50mg","100mg"]},
  {name:"Valsartan",generic:"Diovan",strengths:["40mg","80mg","160mg","320mg"]},
  {name:"Metoprolol Succinate",generic:"Toprol-XL",strengths:["25mg","50mg","100mg","200mg"]},
  {name:"Metoprolol Tartrate",generic:"Lopressor",strengths:["25mg","50mg","100mg"]},
  {name:"Atenolol",generic:"Tenormin",strengths:["25mg","50mg","100mg"]},
  {name:"Propranolol",generic:"Inderal",strengths:["10mg","20mg","40mg","80mg"]},
  {name:"Carvedilol",generic:"Coreg",strengths:["3.125mg","6.25mg","12.5mg","25mg"]},
  {name:"Hydrochlorothiazide",generic:"HCTZ",strengths:["12.5mg","25mg","50mg"]},
  {name:"Furosemide",generic:"Lasix",strengths:["20mg","40mg","80mg"]},
  {name:"Spironolactone",generic:"Aldactone",strengths:["25mg","50mg","100mg"]},
  {name:"Levothyroxine",generic:"Synthroid",strengths:["25mcg","50mcg","75mcg","88mcg","100mcg","112mcg","125mcg","137mcg","150mcg","175mcg","200mcg"]},
  {name:"Sertraline",generic:"Zoloft",strengths:["25mg","50mg","100mg"]},
  {name:"Escitalopram",generic:"Lexapro",strengths:["5mg","10mg","20mg"]},
  {name:"Fluoxetine",generic:"Prozac",strengths:["10mg","20mg","40mg","60mg"]},
  {name:"Citalopram",generic:"Celexa",strengths:["10mg","20mg","40mg"]},
  {name:"Paroxetine",generic:"Paxil",strengths:["10mg","20mg","30mg","40mg"]},
  {name:"Venlafaxine",generic:"Effexor",strengths:["37.5mg","75mg","150mg","225mg"]},
  {name:"Duloxetine",generic:"Cymbalta",strengths:["20mg","30mg","60mg"]},
  {name:"Bupropion",generic:"Wellbutrin",strengths:["75mg","100mg","150mg","300mg"]},
  {name:"Trazodone",generic:"Desyrel",strengths:["50mg","100mg","150mg"]},
  {name:"Mirtazapine",generic:"Remeron",strengths:["7.5mg","15mg","30mg","45mg"]},
  {name:"Alprazolam",generic:"Xanax",strengths:["0.25mg","0.5mg","1mg","2mg"]},
  {name:"Lorazepam",generic:"Ativan",strengths:["0.5mg","1mg","2mg"]},
  {name:"Clonazepam",generic:"Klonopin",strengths:["0.5mg","1mg","2mg"]},
  {name:"Diazepam",generic:"Valium",strengths:["2mg","5mg","10mg"]},
  {name:"Gabapentin",generic:"Neurontin",strengths:["100mg","300mg","400mg","600mg","800mg"]},
  {name:"Pregabalin",generic:"Lyrica",strengths:["25mg","50mg","75mg","100mg","150mg","200mg","300mg"]},
  {name:"Amoxicillin",strengths:["250mg","500mg","875mg"]},
  {name:"Azithromycin",generic:"Z-Pack",strengths:["250mg","500mg"]},
  {name:"Amoxicillin-Clavulanate",generic:"Augmentin",strengths:["500/125mg","875/125mg"]},
  {name:"Ciprofloxacin",generic:"Cipro",strengths:["250mg","500mg","750mg"]},
  {name:"Doxycycline",strengths:["50mg","100mg"]},
  {name:"Cephalexin",generic:"Keflex",strengths:["250mg","500mg"]},
  {name:"Levofloxacin",generic:"Levaquin",strengths:["250mg","500mg","750mg"]},
  {name:"Prednisone",generic:"Deltasone",strengths:["1mg","2.5mg","5mg","10mg","20mg","50mg"]},
  {name:"Methylprednisolone",generic:"Medrol",strengths:["4mg","8mg","16mg","32mg"]},
  {name:"Ibuprofen",generic:"Advil",strengths:["200mg","400mg","600mg","800mg"]},
  {name:"Naproxen",generic:"Aleve",strengths:["220mg","250mg","375mg","500mg"]},
  {name:"Meloxicam",generic:"Mobic",strengths:["7.5mg","15mg"]},
  {name:"Celecoxib",generic:"Celebrex",strengths:["100mg","200mg"]},
  {name:"Acetaminophen",generic:"Tylenol",strengths:["325mg","500mg","650mg","1000mg"]},
  {name:"Tramadol",generic:"Ultram",strengths:["50mg","100mg"]},
  {name:"Cyclobenzaprine",generic:"Flexeril",strengths:["5mg","10mg"]},
  {name:"Albuterol Inhaler",generic:"ProAir/Ventolin",strengths:["90mcg/actuation"]},
  {name:"Fluticasone Inhaler",generic:"Flovent",strengths:["44mcg","110mcg","220mcg"]},
  {name:"Fluticasone-Salmeterol",generic:"Advair",strengths:["100/50mcg","250/50mcg","500/50mcg"]},
  {name:"Budesonide-Formoterol",generic:"Symbicort",strengths:["80/4.5mcg","160/4.5mcg"]},
  {name:"Montelukast",generic:"Singulair",strengths:["4mg","5mg","10mg"]},
  {name:"Cetirizine",generic:"Zyrtec",strengths:["5mg","10mg"]},
  {name:"Loratadine",generic:"Claritin",strengths:["10mg"]},
  {name:"Fexofenadine",generic:"Allegra",strengths:["60mg","180mg"]},
  {name:"Fluticasone Nasal Spray",generic:"Flonase",strengths:["50mcg/spray"]},
  {name:"Insulin Glargine",generic:"Lantus",strengths:["100 units/mL"]},
  {name:"Insulin Lispro",generic:"Humalog",strengths:["100 units/mL"]},
  {name:"Insulin Aspart",generic:"NovoLog",strengths:["100 units/mL"]},
  {name:"Glipizide",generic:"Glucotrol",strengths:["5mg","10mg"]},
  {name:"Glimepiride",generic:"Amaryl",strengths:["1mg","2mg","4mg"]},
  {name:"Pioglitazone",generic:"Actos",strengths:["15mg","30mg","45mg"]},
  {name:"Sitagliptin",generic:"Januvia",strengths:["25mg","50mg","100mg"]},
  {name:"Empagliflozin",generic:"Jardiance",strengths:["10mg","25mg"]},
  {name:"Dapagliflozin",generic:"Farxiga",strengths:["5mg","10mg"]},
  {name:"Semaglutide",generic:"Ozempic/Wegovy",strengths:["0.25mg","0.5mg","1mg","2mg","2.4mg"]},
  {name:"Liraglutide",generic:"Victoza/Saxenda",strengths:["0.6mg","1.2mg","1.8mg","3mg"]},
  {name:"Tirzepatide",generic:"Mounjaro/Zepbound",strengths:["2.5mg","5mg","7.5mg","10mg","12.5mg","15mg"]},
  {name:"Warfarin",generic:"Coumadin",strengths:["1mg","2mg","2.5mg","3mg","4mg","5mg","6mg","7.5mg","10mg"]},
  {name:"Apixaban",generic:"Eliquis",strengths:["2.5mg","5mg"]},
  {name:"Rivaroxaban",generic:"Xarelto",strengths:["2.5mg","10mg","15mg","20mg"]},
  {name:"Clopidogrel",generic:"Plavix",strengths:["75mg"]},
  {name:"Aspirin",strengths:["81mg","325mg"]},
  {name:"Tamsulosin",generic:"Flomax",strengths:["0.4mg"]},
  {name:"Finasteride",generic:"Proscar",strengths:["1mg","5mg"]},
  {name:"Sildenafil",generic:"Viagra",strengths:["25mg","50mg","100mg"]},
  {name:"Tadalafil",generic:"Cialis",strengths:["2.5mg","5mg","10mg","20mg"]},
  {name:"Estradiol",generic:"Estrace",strengths:["0.5mg","1mg","2mg"]},
  {name:"Progesterone",generic:"Prometrium",strengths:["100mg","200mg"]},
  {name:"Norethindrone",generic:"Aygestin",strengths:["5mg"]},
  {name:"Testosterone Cypionate",generic:"Depo-Testosterone",strengths:["100mg/mL","200mg/mL"]},
  {name:"Zolpidem",generic:"Ambien",strengths:["5mg","10mg"]},
  {name:"Suvorexant",generic:"Belsomra",strengths:["5mg","10mg","15mg","20mg"]},
  {name:"Hydroxyzine",generic:"Vistaril",strengths:["10mg","25mg","50mg"]},
  {name:"Ondansetron",generic:"Zofran",strengths:["4mg","8mg"]},
  {name:"Oxycodone",generic:"OxyContin",strengths:["5mg","10mg","15mg","20mg","30mg"]},
  {name:"Hydrocodone-Acetaminophen",generic:"Vicodin/Norco",strengths:["5/325mg","7.5/325mg","10/325mg"]},
  {name:"Morphine",generic:"MS Contin",strengths:["15mg","30mg","60mg"]},
  {name:"Aripiprazole",generic:"Abilify",strengths:["2mg","5mg","10mg","15mg","20mg","30mg"]},
  {name:"Quetiapine",generic:"Seroquel",strengths:["25mg","50mg","100mg","200mg","300mg","400mg"]},
  {name:"Olanzapine",generic:"Zyprexa",strengths:["2.5mg","5mg","10mg","15mg","20mg"]},
  {name:"Risperidone",generic:"Risperdal",strengths:["0.25mg","0.5mg","1mg","2mg","3mg","4mg"]},
  {name:"Lamotrigine",generic:"Lamictal",strengths:["25mg","100mg","150mg","200mg"]},
  {name:"Lithium Carbonate",generic:"Lithobid",strengths:["150mg","300mg","600mg"]},
  {name:"Valproic Acid",generic:"Depakote",strengths:["125mg","250mg","500mg"]},
  {name:"Topiramate",generic:"Topamax",strengths:["25mg","50mg","100mg","200mg"]},
  {name:"Levetiracetam",generic:"Keppra",strengths:["250mg","500mg","750mg","1000mg"]},
  {name:"Methylphenidate",generic:"Ritalin/Concerta",strengths:["5mg","10mg","18mg","27mg","36mg","54mg"]},
  {name:"Amphetamine-Dextroamphetamine",generic:"Adderall",strengths:["5mg","10mg","15mg","20mg","25mg","30mg"]},
  {name:"Lisdexamfetamine",generic:"Vyvanse",strengths:["10mg","20mg","30mg","40mg","50mg","60mg","70mg"]},
  {name:"Atomoxetine",generic:"Strattera",strengths:["10mg","18mg","25mg","40mg","60mg","80mg","100mg"]},
  {name:"Latanoprost",generic:"Xalatan",strengths:["0.005%"]},
  {name:"Timolol",generic:"Timoptic",strengths:["0.25%","0.5%"]},
  {name:"Methotrexate",generic:"Trexall",strengths:["2.5mg","5mg","7.5mg","10mg","15mg"]},
  {name:"Adalimumab",generic:"Humira",strengths:["40mg"]},
  {name:"Etanercept",generic:"Enbrel",strengths:["25mg","50mg"]},
  {name:"Allopurinol",generic:"Zyloprim",strengths:["100mg","300mg"]},
  {name:"Colchicine",generic:"Colcrys",strengths:["0.6mg"]},
  {name:"Baclofen",generic:"Lioresal",strengths:["5mg","10mg","20mg"]},
  {name:"Ranitidine",generic:"Zantac",strengths:["75mg","150mg","300mg"]},
  {name:"Famotidine",generic:"Pepcid",strengths:["10mg","20mg","40mg"]},
  {name:"Sucralfate",generic:"Carafate",strengths:["1g"]},
  {name:"Dicyclomine",generic:"Bentyl",strengths:["10mg","20mg"]},
  {name:"Polyethylene Glycol",generic:"MiraLAX",strengths:["17g"]},
  {name:"Docusate Sodium",generic:"Colace",strengths:["100mg","250mg"]},
  {name:"Linaclotide",generic:"Linzess",strengths:["72mcg","145mcg","290mcg"]},
  {name:"Mesalamine",generic:"Lialda",strengths:["400mg","800mg","1.2g"]},
  {name:"Sumatriptan",generic:"Imitrex",strengths:["25mg","50mg","100mg"]},
  {name:"Rizatriptan",generic:"Maxalt",strengths:["5mg","10mg"]},
];
